system:
    default:
        content_view:
            line:
                pjax_line:
                    template: "eZPlatformUIBundle:content:line.html.twig"
                    match:
                        ezsystems.platformui.view_matcher.pjax_request: true
    admin:
        content_view:
            full:
                default:
                    template: "eZPlatformUIBundle:PlatformUI:locationview.html.twig"
                    controller: "eZPlatformUIBundle:ProtoBD:locationView"
                    match: true
