v: 0

# This is a bundle, so we need to specify info for meta repo
meta:
  repo: "https://github.com/ezsystems/ezplatform.git"
  branch: "master"
  self_alias: "1.0.x-dev"

# ci
integrate:
  command: "bin/behat"
  matrix:
  # Run 'common' tagged behat scenarios on ezplatform install
   - {arguments: "-v --profile platformui --tags common", install: "clean"}
