/*
 * Copyright (C) eZ Systems AS. All rights reserved.
 * For full copyright and license information view LICENSE file distributed with this source code.
 */
YUI.add('ez-alloyeditor-button-heading-tests', function (Y) {
    var renderTest, clickTest,
        AlloyEditor = Y.eZ.AlloyEditor,
        React = Y.eZ.React,
        Assert = Y.Assert, Mock = Y.Mock;

    renderTest = new Y.Test.Case({
        name: "eZ AlloyEditor heading button render test",

        setUp: function () {
            this.container = Y.one('.container').getDOMNode();
            this.editor = {};
        },

        tearDown: function () {
            React.unmountComponentAtNode(this.container);
            delete this.editor;
        },

        "Should render a button": function () {
            var button;

            button = React.render(
                <AlloyEditor.ButtonHeading editor={this.editor} />,
                this.container
            );

            Assert.isNotNull(
                React.findDOMNode(button),
                "The button should be rendered"
            );
            Assert.areEqual(
                "BUTTON", React.findDOMNode(button).tagName,
                "The component should generate a button"
            );
        },
    });

    clickTest= new Y.Test.Case({
        name: "eZ AlloyEditor heading button click test",

        setUp: function () {
            var nat = new Mock();

            this.container = Y.one('.container');
            this.editor = new Mock();
            Mock.expect(this.editor, {
                method: 'get',
                args: ['nativeEditor'],
                returns: nat,
            });
            Mock.expect(nat, {
                method: 'execCommand',
                args: ['eZAddContent', Mock.Value.Object],
                run: function (command, data) {
                    Assert.areEqual(
                        data.tagName, 'h1',
                        "A h1 should be generated by default"
                    );
                }
            });
            Mock.expect(nat, {
                method: 'selectionChange',
                args: [true],
            });
            Mock.expect(nat, {
                method: 'fire',
                args: ['actionPerformed', Mock.Value.Object],
            });
        },

        tearDown: function () {
            React.unmountComponentAtNode(this.container.getDOMNode());
            delete this.editor;
        },

        "Should execute the eZAddContent command": function () {
            var button;

            button = React.render(
                <AlloyEditor.ButtonHeading editor={this.editor} />,
                this.container.getDOMNode()
            );

            this.container.one('button').simulate('click');
        },
    });

    Y.Test.Runner.setName("eZ AlloyEditor heading button tests");
    Y.Test.Runner.add(renderTest);
    Y.Test.Runner.add(clickTest);
}, '', {requires: ['test', 'node', 'node-event-simulate', 'ez-alloyeditor-button-heading']});
